using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerInitializer : MonoBehaviour
{
    [SerializeField] public string userId; // Inspector에서 설정 가능

    void Start()
    {
        VoiceManager voiceManager = GetComponent<VoiceManager>();
        if (voiceManager != null)
        {
            NetworkManager.Instance.RegisterUser(voiceManager, userId);
        }
        else
        {
            Debug.LogError("VoiceManager 컴포넌트를 찾을 수 없습니다!");
        }
    }
    // Player ID를 자동 생성하려면 아래의 코드를 이용하면 됨
    //void Start()
    //{
    //    VoiceManager voiceManager = GetComponent<VoiceManager>();
    //    string autoGeneratedId = $"User_{System.Guid.NewGuid().ToString("N").Substring(0, 8)}";
    //    NetworkManager.Instance.RegisterUser(voiceManager, autoGeneratedId);
    //}
}